# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/todo-lists
Content-Type: application/json

{
  "id": "77a9d273-441c-4ca6-a493-f617df6b5a23",
  "name": "my todo list"
}

###

# curl -X POST http://localhost:8080/todo-lists
#  -H 'Content-Type: application/json'
#  -d '{"name": "John"}'
POST http://localhost:3000/hub/pdf/us-direct-deposit-form/raw
Content-Type: application/json

{
  "name": "John"
}

###


